In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import Lasso, Ridge, LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

from xgboost import XGBRegressor

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam

pd.pandas.set_option('display.max_columns', None)

C:\Users\Prestela\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Prestela\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Prestela\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Prestela\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWa

In [2]:
selected_features = pd.read_csv('Selected_features.csv',header=None)
features = selected_features[0].tolist()
features

['MSSubClass',
 'LotFrontage',
 'LotArea',
 'LotShape',
 'LotConfig',
 'Neighborhood',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrArea',
 'BsmtQual',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'HeatingQC',
 '1stFlrSF',
 '2ndFlrSF',
 'GrLivArea',
 'BedroomAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 'ScreenPorch',
 'MoSold',
 'YrSold']

In [3]:
train = pd.read_csv('New_Train.csv')

In [4]:
test = pd.read_csv('New_Test.csv')
test

Id  MSSubClass  MSZoning  LotFrontage   LotArea  Street  Alley  \
0     1461.0    0.000000       0.5     0.329609  0.184147     1.0    1.0   
1     1462.0    0.000000       1.0     0.335196  0.232124     1.0    1.0   
2     1463.0    0.235294       1.0     0.296089  0.224197     1.0    1.0   
3     1464.0    0.235294       1.0     0.318436  0.154326     1.0    1.0   
4     1465.0    0.588235       1.0     0.122905  0.064121     1.0    1.0   
5     1466.0    0.235294       1.0     0.301676  0.154725     1.0    1.0   
6     1467.0    0.000000       1.0     0.268156  0.118085     1.0    1.0   
7     1468.0    0.235294       1.0     0.234637  0.125739     1.0    1.0   
8     1469.0    0.000000       1.0     0.357542  0.157918     1.0    1.0   
9     1470.0    0.000000       1.0     0.273743  0.125703     1.0    1.0   
10    1471.0    0.588235       0.5     0.027933  0.079594     1.0    1.0   
11    1472.0    0.823529       0.0     0.000000  0.003809     1.0    1.0   
12    1473.0    0.823529       0.0     0.000000  0.003809     1.0    1.0   
13    1474.0    0.823529       1.0     0.016760  0.014693     1.0    1.0   
14    1475.0    0.588235       1.0     0.016760  0.014693     1.0    1.0   
15    1476.0    0.235294       1.0     0.452514  0.206566     1.0    1.0   
16    1477.0    0.000000       1.0     0.407821  0.207020     1.0    1.0   
17    1478.0    0.000000       1.0     0.385475  0.182296     1.0    1.0   
18    1479.0    0.000000       1.0     0.324022  0.229494     1.0    1.0   
19    1480.0    0.000000       1.0     0.497207  0.232723     1.0    1.0   
20    1481.0    0.235294       1.0     0.469274  0.220932     1.0    1.0   
21    1482.0    0.588235       1.0     0.111732  0.102703     1.0    1.0   
22    1483.0    0.000000       1.0     0.441341  0.308797     1.0    1.0   
23    1484.0    0.588235       1.0     0.122905  0.031435     1.0    1.0   
24    1485.0    0.352941       1.0     0.256983  0.214584     1.0    1.0   
25    1486.0    0.235294       1.0     0.234637  0.128913     1.0    1.0   
26    1487.0    0.235294       1.0     0.217877  0.289552     1.0    1.0   
27    1488.0    0.000000       1.0     0.290503  0.136350     1.0    1.0   
28    1489.0    0.000000       0.5     0.396648  0.140486     1.0    1.0   
29    1490.0    0.000000       0.5     0.351955  0.162706     1.0    1.0   
...      ...         ...       ...          ...       ...     ...    ...   
1429  2890.0    0.058824       0.0     0.162011  0.100853     1.0    1.0   
1430  2891.0    0.176471       0.0     0.301676  0.137675     1.0    1.0   
1431  2892.0    0.058824       0.5     0.268156  0.197642     1.0    1.0   
1432  2893.0    1.000000       0.5     0.162011  0.136586     1.0    1.0   
1433  2894.0    0.176471       0.5     0.217877  0.127880     0.0    1.0   
1434  2895.0    0.588235       0.0     0.111732  0.077598     1.0    1.0   
1435  2896.0    0.588235       0.0     0.128492  0.043026     1.0    1.0   
1436  2897.0    0.000000       1.0     0.268156  0.401052     1.0    1.0   
1437  2898.0    0.411765       1.0     0.245810  0.125431     1.0    1.0   
1438  2899.0    0.000000       1.0     0.273743  0.138690     1.0    1.0   
1439  2900.0    0.352941       1.0     0.664804  0.174315     1.0    1.0   
1440  2901.0    0.000000       1.0     0.268156  0.882133     1.0    1.0   
1441  2902.0    0.000000       1.0     0.268156  0.120225     1.0    1.0   
1442  2903.0    0.000000       1.0     0.413408  0.220352     1.0    1.0   
1443  2904.0    0.000000       1.0     0.374302  0.183330     1.0    1.0   
1444  2905.0    0.000000       0.5     0.581006  0.540178     1.0    1.0   
1445  2906.0    0.411765       0.0     0.318436  0.100671     1.0    1.0   
1446  2907.0    0.823529       0.0     0.111732  0.021676     1.0    1.0   
1447  2908.0    0.000000       1.0     0.206704  0.157845     1.0    1.0   
1448  2909.0    0.411765       1.0     0.268156  0.188028     1.0    1.0   
1449  2910.0    0.941176       0.0     0.000000  0.000000 

In [5]:
linear_model = LinearRegression()

In [6]:
X_train=train[features].to_numpy()
X_test=test[features].to_numpy()

In [7]:
y_train=train["SalePrice"].to_numpy()
y_test=test["SalePrice"].to_numpy()

***Linear Regression Model***

In [8]:
linear_model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
X_test
X_test.shape

(1459, 39)

In [10]:
y_test.shape
#y_test

(1459,)

In [11]:
y_pred_lm = linear_model.predict(X_test)
y_pred_lm.shape

(1459,)

In [12]:
linear_model.coef_

array([-37260.49697876, -31012.43129942,  80464.93116565,    193.6278185 ,
         4277.49487121,  27297.39546711, 117391.81427771,  34631.60697263,
        19818.34175842,  -2135.8050444 ,   2335.26417292,  -2562.34626102,
        48044.32880542,  33780.84162199,  24836.95122976,  -2095.91330773,
        35341.64710278,  -5693.68176182, -18950.27179998,  24027.4851729 ,
         5843.95065538, 167576.57450835,  63659.71141438,  95640.70706958,
       -50211.25766154,  38107.39918875,  48215.71271438,   6104.0773887 ,
         5056.99442157,  -8196.06537995,   2508.73637082,   4403.82765259,
        31992.11671367,  15308.25534012,  -5431.35607376,   3790.99136014,
        24152.77641084,  -1187.73893263,   -517.0469089 ])

In [13]:
mse_1 = mean_squared_error(y_test, y_pred_lm)

In [14]:
r2_1 = r2_score(y_test, y_pred_lm)

In [15]:
y_test

array([0.22979726, 0.35647493, 0.32785999, ..., 0.57214055, 0.33704891,
       0.35636165])

In [16]:
y_pred_lm

array([119019.56957555, 168568.93519174, 169863.31671285, ...,
       150247.80737412, 107757.88269351, 239365.68129485])

In [17]:
y_train

array([208500, 181500, 223500, ..., 266500, 142125, 147500], dtype=int64)

In [18]:
#for var in features:
#    plt.scatter(train[var], y_train)
#    plt.title(var)
#    plt.show()

***XGBoost***

In [30]:
xgboost = XGBRegressor()

In [31]:
xgboost.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=0, num_parallel_tree=1,
             objective='reg:squarederror', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [48]:
y_pred_xgb = xgboost.predict(X_test)
y_pred_xgb

array([146447.16, 142257.38, 206916.9 , ..., 173961.94, 120376.46,
       253376.61], dtype=float32)

In [33]:
mse_2 = mean_squared_error(y_test, y_pred_xgb)

In [34]:
r2_score(y_test, y_pred_xgb)

-3191309849549.903

In [35]:
mse_1

35278610288.72705

***Neural Network***

In [36]:
model = Sequential()
model.add(Dense(6, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1))

model.compile(optimizer='Adam', loss='mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [62]:
model.fit(x=X_train, y=y_train,
         validation_data=(X_test, y_test),
         batch_size=200, epochs=400)

Train on 1460 samples, validate on 1459 samples
Epoch 1/400
1460/1460 [==============================] - 0s 151us/sample - loss: 2048030620.0548 - val_loss: 37458054614.9417
Epoch 2/400
1460/1460 [==============================] - 0s 133us/sample - loss: 2046582328.1096 - val_loss: 37494303945.4311
Epoch 3/400
1460/1460 [==============================] - 0s 188us/sample - loss: 2045194303.1233 - val_loss: 37541831326.9692
Epoch 4/400
1460/1460 [==============================] - 0s 117us/sample - loss: 2044026189.1507 - val_loss: 37479100752.8883
Epoch 5/400
1460/1460 [==============================] - 0s 89us/sample - loss: 2042332302.0274 - val_loss: 37537384727.3365
Epoch 6/400
1460/1460 [==============================] - 0s 103us/sample - loss: 2040630345.6438 - val_loss: 37512903039.2104
Epoch 7/400
1460/1460 [==============================] - 0s 102us/sample - loss: 2039217830.5753 - val_loss: 37536803727.0021
Epoch 8/400
1460/1460 [==============================] - 0s 135us/sampl

Epoch 130/400
1460/1460 [==============================] - 0s 38us/sample - loss: 1851521521.9726 - val_loss: 37629022536.4661
Epoch 131/400
1460/1460 [==============================] - 0s 23us/sample - loss: 1849754816.8767 - val_loss: 37730514569.2118
Epoch 132/400
1460/1460 [==============================] - 0s 36us/sample - loss: 1848898654.6849 - val_loss: 37922777816.5209
Epoch 133/400
1460/1460 [==============================] - 0s 57us/sample - loss: 1847589703.8904 - val_loss: 37911987074.3687
Epoch 134/400
1460/1460 [==============================] - 0s 40us/sample - loss: 1846142478.0274 - val_loss: 37872695519.1885
Epoch 135/400
1460/1460 [==============================] - 0s 105us/sample - loss: 1844443523.5068 - val_loss: 37826633231.0898
Epoch 136/400
1460/1460 [==============================] - 0s 74us/sample - loss: 1842997663.5616 - val_loss: 37702379953.7437
Epoch 137/400
1460/1460 [==============================] - 0s 32us/sample - loss: 1841054016.8767 - val_loss: 

1460/1460 [==============================] - 0s 31us/sample - loss: 1671191779.9452 - val_loss: 37589815186.5113
Epoch 259/400
1460/1460 [==============================] - 0s 67us/sample - loss: 1669883861.9178 - val_loss: 37607594372.8252
Epoch 260/400
1460/1460 [==============================] - 0s 81us/sample - loss: 1668508757.9178 - val_loss: 37538289381.8561
Epoch 261/400
1460/1460 [==============================] - 0s 56us/sample - loss: 1667486805.9178 - val_loss: 37521891524.5182
Epoch 262/400
1460/1460 [==============================] - 0s 78us/sample - loss: 1666030960.2192 - val_loss: 37588938819.3777
Epoch 263/400
1460/1460 [==============================] - 0s 36us/sample - loss: 1664748061.8082 - val_loss: 37575012767.4955
Epoch 264/400
1460/1460 [==============================] - 0s 40us/sample - loss: 1663112097.3151 - val_loss: 37669977146.2536
Epoch 265/400
1460/1460 [==============================] - 0s 73us/sample - loss: 1661356403.7260 - val_loss: 37877429671.215

1460/1460 [==============================] - 0s 42us/sample - loss: 1522743381.9178 - val_loss: 37758595296.5922
Epoch 387/400
1460/1460 [==============================] - 0s 82us/sample - loss: 1521984883.7260 - val_loss: 37584697637.3735
Epoch 388/400
1460/1460 [==============================] - 0s 55us/sample - loss: 1522239039.1233 - val_loss: 37496763311.2872
Epoch 389/400
1460/1460 [==============================] - 0s 66us/sample - loss: 1520013590.7945 - val_loss: 37709029940.2879
Epoch 390/400
1460/1460 [==============================] - 0s 70us/sample - loss: 1518474897.9726 - val_loss: 37832629783.5120
Epoch 391/400
1460/1460 [==============================] - 0s 46us/sample - loss: 1517807564.2740 - val_loss: 37951497668.6936
Epoch 392/400
1460/1460 [==============================] - 0s 35us/sample - loss: 1516897365.9178 - val_loss: 37952821597.5216
Epoch 393/400
1460/1460 [==============================] - 0s 85us/sample - loss: 1516067596.2740 - val_loss: 38036579878.952

In [63]:
y_pred_nn=model.predict(X_test)
y_pred_nn

array([[128058.586],
       [163894.11 ],
       [205794.52 ],
       ...,
       [190067.92 ],
       [122809.76 ],
       [233273.7  ]], dtype=float32)

In [64]:
mse_3 = model.evaluate(X_test,y_test)

1459/1459 [==============================] - 0s 23us/sample - loss: 37738016308.9897


In [75]:
mse_3
np.var(y_pred_nn)

4089081300.0

In [66]:
print(f'Linear Regression: {mse_1}')
print(f'XGBoost: {mse_2}')
print(f'Neural Network: {mse_3}')

Linear Regression: 35278610288.72705
XGBoost: 40882288160.14717
Neural Network: 37738016308.989716


In [67]:
min(mse_1,mse_2,mse_3)

35278610288.72705

In [68]:
predictions = pd.DataFrame(y_pred_lm)


In [69]:
predictions = pd.concat([test['Id'], predictions], axis=1)

In [70]:
predictions['Id']=predictions['Id'].astype('int64')

In [71]:
predictions


Id              0
0     1461  119019.569576
1     1462  168568.935192
2     1463  169863.316713
3     1464  188892.857055
4     1465  174378.924630
5     1466  169932.795935
6     1467  170649.349325
7     1468  157502.916447
8     1469  212484.583784
9     1470   97204.739139
10    1471  182022.091290
11    1472  106903.646314
12    1473   95399.314388
13    1474  133793.591804
14    1475  107033.825892
15    1476  319247.089132
16    1477  236758.168932
17    1478  298924.369264
18    1479  282195.257315
19    1480  427577.189839
20    1481  297980.773611
21    1482  210872.990681
22    1483  175224.530686
23    1484  159753.990955
24    1485  189636.896757
25    1486  201298.170473
26    1487  292598.601911
27    1488  236311.824169
28    1489  177521.233085
29    1490  241071.121933
...    ...            ...
1429  2890   52610.218822
1430  2891  155617.119183
1431  2892   40014.022013
1432  2893   85321.503643
1433  2894   43471.662129
1434  2895  296739.837156
1435  2896  261975.467948
1436  2897  208522.549983
1437  2898  147942.813043
1438  2899  213055.457022
1439  2900  139136.366624
1440  2901  272535.495791
1441  2902  195843.803545
1442  2903  303150.601779
1443  2904  321163.343905
1444  2905   73891.910335
1445  2906  210950.796977
1446  2907  100200.084045
1447  2908  104953.988594
1448  2909  137532.318447
1449  2910   60347.332446
1450  2911   49255.921887
1451  2912  154733.567359
1452  2913   58181.762869
1453  2914   44202.802972
1454  2915   55655.979473
1455  2916   60658.460229
1456  2917  150247.807374
1457  2918  107757.882694
1458  2919  239365.681295

[1459 rows x 2 columns]

In [73]:
predictions.to_csv('HousePrice_Predictions.csv')